name: Validate assets and HTML

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies (none)
        run: echo "No npm deps"
      - name: Fetch assets
        run: node tools/fetch-assets.mjs
      - name: Run validator
        run: node tools/ci-validate.mjs
